# These are supported funding model platforms
buy_me_a_coffee: pankajkuma7    # Your Buy Me a Coffee username
custom:
  - "https://upi.me/pay?pa=pankajkumardas8678@ybl"   # Replace with your actual UPI ID link

