CREATE DATABASE IF NOT EXISTS PHP_BASIC_PROJECTS;
use PHP_BASIC_PROJECTS;
CREATE TABLE students
(

    ID int(100) AUTO_INCREMENT PRIMARY KEY ,
    NAME VARCHAR(100) NOT NULL,
    COURSE VARCHAR(100) NOT NULL,
    EMAIL VARCHAR(20) NOT NULL

);


INSERT INTO students (ID, NAME , COURSE, EMAIL )
VALUES(1 , 'PANKAJ KUMAR DAS', 'BCA', 'admin@123');