CREATE DATABASE IF NOT EXISTS PHP_BASIC_PROJECTS;
use PHP_BASIC_PROJECTS;
CREATE TABLE users
(

    ID int(100) AUTO_INCREMENT PRIMARY KEY ,
    EMAIL VARCHAR(20) NOT NULL,
    PASSWORD VARCHAR(20)

);


INSERT INTO users (ID , EMAIL , PASSWORD)
VALUES(1 , 'admin@gmail.com' , 'admin@123');